exec('6_07data.sci')
a=atand(1/L_D);disp(a,"a=","tan(a)=1/(L/D)","minimum glide angle a:")
R=H*L_D;disp(R,"R=","R=H*L/D","maximum range along ground :")
printf("\Answer:\n")
printf("\minimum glide angle: %f \n",a)
printf("\n\maximum range covered along ground: %f m\n\n",R)